version: '2'
services:
    tweet-app:
        image: tweet
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://tweet-mysql:3306/tweet?useUnicode=true&characterEncoding=utf8&useSSL=false
            - SECURITY_OAUTH2_CLIENT_ACCESS_TOKEN_URI=http://keycloak:9080/auth/realms/jhipster/protocol/openid-connect/token
            - SECURITY_OAUTH2_CLIENT_USER_AUTHORIZATION_URI=http://keycloak:9080/auth/realms/jhipster/protocol/openid-connect/auth
            - SECURITY_OAUTH2_CLIENT_CLIENT_ID=web_app
            - SECURITY_OAUTH2_CLIENT_CLIENT_SECRET=web_app
            - SECURITY_OAUTH2_CLIENT_SCOPE=openid profile email
            - SECURITY_OAUTH2_RESOURCE_USER_INFO_URI=http://keycloak:9080/auth/realms/jhipster/protocol/openid-connect/userinfo
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=tweet-elasticsearch:9300
        ports:
            - 8081:8081
    tweet-mysql:
        extends:
            file: mysql.yml
            service: tweet-mysql
    tweet-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: tweet-elasticsearch
    keycloak:
        extends:
            file: keycloak.yml
            service: keycloak
